name: weewee_delivery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.0.1
  dropdown_button2: ^2.0.0
  bottom_picker: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  salomon_bottom_bar: ^3.3.2
  circular_menu: ^2.0.1
  auto_animated: ^3.1.0
  flutter_bloc: ^8.1.2
  syncfusion_flutter_charts: ^21.1.39
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_phone_auth_handler: ^1.0.7
  pin_code_fields: ^7.4.0
  json_annotation: ^4.8.0
  loading_animation_widget: ^1.2.0+4
  qr_code_scanner: ^1.0.1
  fluttertoast: ^8.2.1
  google_maps_flutter: ^2.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3





































# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/logo.png
    - assets/icons/arrow-right.png
    - assets/icons/driver.png
    - assets/icons/trader.png
    - assets/onboarding/onboarding.jpg
    - assets/onboarding/slide1.json
    - assets/onboarding/slide2.json
    - assets/onboarding/slide3.json
    - assets/onboarding/slide4.json
    - assets/icons/automobile.png
    - assets/icons/cycle.png
    - assets/icons/motorbiking.png
    - assets/icons/suv.png
    - assets/icons/tourist.png
    - assets/icons/truck1.png
    - assets/icons/truck2.png
    - assets/icons/walking.png
    - assets/icons/package.png
    - assets/icons/packagelogo.png
    - assets/icons/done.png
    - assets/icons/qrcode.png
    - assets/icons/person.png
    - assets/icons/phone.png
    - assets/icons/location.png
    - assets/icons/down-arrow.png
    - assets/icons/logout.png
    - assets/icons/edit.png
    - assets/icons/half-circle.png
    - assets/icons/product.png
    - assets/icons/order.png
    - assets/icons/approved.png
    - assets/icons/packages.png
    - assets/icons/pickup.png
    - assets/icons/returned.png
    - assets/icons/add-client.png
    - assets/icons/store.png
    - assets/icons/open-box.png
    - assets/icons/privacy-policy.png
    - assets/icons/delivery-cost.png
    - assets/icons/wallet.png
    - assets/icons/closed.png
    - assets/icons/delivery-truck-return.png
    - assets/icons/online.png
    - assets/icons/inroad.png
    - assets/icons/coment.png
    - assets/icons/warning.png
    - assets/icons/empty.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
