// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'package_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Package _$PackageFromJson(Map<String, dynamic> json) => Package(
      id: json['id'] as String?,
      packageCreatedAt: json['packageCreatedAt'] as String,
      packageState: json['packageState'] as String,
      isFreeDelivery: json['isFreeDelivery'] as bool,
      preferredDeliveryDay: json['preferredDeliveryDay'] as String,
      preferredDeliveryTime: json['preferredDeliveryTime'] as String,
      deliveryCost: json['deliveryCost'] as bool,
      senderFullName: json['senderFullName'] as String,
      senderStoreName: json['senderStoreName'] as String,
      senderMobileNumber: json['senderMobileNumber'] as String,
      senderWilaia: json['senderWilaia'] as String,
      senderBaladia: json['senderBaladia'] as String,
      senderAddress: json['senderAddress'] as String,
      senderGeolocation: json['senderGeolocation'] as String,
      senderAnotherStoreName: json['senderAnotherStoreName'] as String,
      senderAnotherMobileNumber: json['senderAnotherMobileNumber'] as String,
      senderAnotherWilaia: json['senderAnotherWilaia'] as String,
      senderAnotherBaladia: json['senderAnotherBaladia'] as String,
      senderAnotherAddress: json['senderAnotherAddress'] as String,
      senderAnotherGeolocation: json['senderAnotherGeolocation'] as String,
      clientFullName: json['clientFullName'] as String,
      clientPhoneNumber: json['clientPhoneNumber'] as String,
      clientOptionalPhoneNumber: json['clientOptionalPhoneNumber'] as String?,
      clientWilaya: json['clientWilaya'] as String,
      clientBaladia: json['clientBaladia'] as String,
      clientAddress: json['clientAddress'] as String,
      clientGeolocation: json['clientGeolocation'] as String?,
      productName: json['productName'] as String,
      productDescription: json['productDescription'] as String,
      productPrice: json['productPrice'] as String,
      productHeight: json['productHeight'] as String,
      productWidth: json['productWidth'] as String,
      productLength: json['productLength'] as String,
      productWeight: json['productWeight'] as String,
      productSelectedFromStock: json['productSelectedFromStock'] as bool,
      productNewStockState: json['productNewStockState'] as String,
    );

Map<String, dynamic> _$PackageToJson(Package instance) => <String, dynamic>{
      'id': instance.id,
      'packageCreatedAt': instance.packageCreatedAt,
      'packageState': instance.packageState,
      'isFreeDelivery': instance.isFreeDelivery,
      'deliveryCost': instance.deliveryCost,
      'preferredDeliveryDay': instance.preferredDeliveryDay,
      'preferredDeliveryTime': instance.preferredDeliveryTime,
      'senderFullName': instance.senderFullName,
      'senderStoreName': instance.senderStoreName,
      'senderMobileNumber': instance.senderMobileNumber,
      'senderWilaia': instance.senderWilaia,
      'senderBaladia': instance.senderBaladia,
      'senderAddress': instance.senderAddress,
      'senderGeolocation': instance.senderGeolocation,
      'senderAnotherStoreName': instance.senderAnotherStoreName,
      'senderAnotherMobileNumber': instance.senderAnotherMobileNumber,
      'senderAnotherWilaia': instance.senderAnotherWilaia,
      'senderAnotherBaladia': instance.senderAnotherBaladia,
      'senderAnotherAddress': instance.senderAnotherAddress,
      'senderAnotherGeolocation': instance.senderAnotherGeolocation,
      'clientFullName': instance.clientFullName,
      'clientPhoneNumber': instance.clientPhoneNumber,
      'clientOptionalPhoneNumber': instance.clientOptionalPhoneNumber,
      'clientWilaya': instance.clientWilaya,
      'clientBaladia': instance.clientBaladia,
      'clientAddress': instance.clientAddress,
      'clientGeolocation': instance.clientGeolocation,
      'productName': instance.productName,
      'productDescription': instance.productDescription,
      'productPrice': instance.productPrice,
      'productHeight': instance.productHeight,
      'productWidth': instance.productWidth,
      'productLength': instance.productLength,
      'productWeight': instance.productWeight,
      'productSelectedFromStock': instance.productSelectedFromStock,
      'productNewStockState': instance.productNewStockState,
    };
