class DeliverFirebaseCubitState {}

class CreateDeliverFirebaseBlocState extends DeliverFirebaseCubitState {}

class GetMyPackagesListLoadingState extends DeliverFirebaseCubitState{}
class GetMyPackagesListSuccessfullyState extends DeliverFirebaseCubitState {}