class DeliverFirebaseCubitState {}

class CreateDeliverFirebaseBlocState extends DeliverFirebaseCubitState {}

class GetMyPackagesListLoadingState extends DeliverFirebaseCubitState{}
class GetMyPackagesListSuccessfullyState extends DeliverFirebaseCubitState {}



class ChangePackageStateLoadingState extends DeliverFirebaseCubitState{}
class ChangePackageStateSuccessfullyState extends DeliverFirebaseCubitState{}


class PickUpPackagesLoadingState extends DeliverFirebaseCubitState{}
class PickUpPackagesSuccessfullyState extends DeliverFirebaseCubitState{}
