class DeliverFirebaseCubitState {}

class CreateDeliverFirebaseBlocState extends DeliverFirebaseCubitState {}

class GetMyPackagesListLoadingState extends DeliverFirebaseCubitState{}
class GetMyPackagesListSuccessfullyState extends DeliverFirebaseCubitState {}



class ChangePackageStateLoadingState extends DeliverFirebaseCubitState{}
class ChangePackageStateSuccessfullyState extends DeliverFirebaseCubitState{}


class PickUpPackagesLoadingState extends DeliverFirebaseCubitState{}
class PickUpPackagesSuccessfullyState extends DeliverFirebaseCubitState{}


class NewWeeWeeWalletLoadingState extends DeliverFirebaseCubitState{}
class NewWeeWeeWalletSuccessfullyState extends DeliverFirebaseCubitState{}

class GetWeeWeeWalletSuccessfullyState extends DeliverFirebaseCubitState{}
class GetWeeWeeWalletLoadingState extends DeliverFirebaseCubitState{}


class GetWalletPackagesListHistoryLoadingState extends DeliverFirebaseCubitState{}
class GetWalletPackagesListHistorySuccessfullyState extends DeliverFirebaseCubitState {}

